#!/bin/sh

CURRENT_BRANCH="$(git branch --show-current)"

FORBIDDEN_BRANCHES="main master"
FORBIDDEN_PATTERNS="release/"

stop_pushing() {
  echo "You can't push directly to $1 branch!"
  exit 1
}

for forbidden_branch in $FORBIDDEN_BRANCHES
do
  if [ "$CURRENT_BRANCH" = "$forbidden_branch" ]
  then
    stop_pushing "$CURRENT_BRANCH"
  fi
done

for forbidden_pattern in $FORBIDDEN_PATTERNS
do
  if [[ $CURRENT_BRANCH = *"$forbidden_pattern"* ]]
  then
    stop_pushing "$CURRENT_BRANCH"
  fi
done

echo "Pushed to $CURRENT_BRANCH"
exit 0
